name: helllo
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    env;
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Hello world action step
        run: echo "Hello world!"
      - name: Print the secret
        run: echo "${PASSWORD}"
      - name: Print the secret
        run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
